# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      run:
        mkdir ~/.ssh
        [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""

# Run deamonized tmate
        echo Running tmate...
        chmod 777 ./tmate
        ./tmate -S /tmp/tmate.sock new-session -d
        ./tmate -S /tmp/tmate.sock wait tmate-ready

# Print connection info
        echo ________________________________________________________________________________
        echo
        echo To connect to this session copy-n-paste the following into a terminal:
        ./tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

        while [ -S /tmp/tmate.sock ]
        do
        sleep 1
        done
      
